### ISSUE TITLE
Public Release

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/enterprise-deployment#27]
Last CTS runs indicate no failures in this component. It's time to make a public release. Before the release make sure that Eclipse Release Review is passed and all dependencies have been released.

**Comment by kwsutter** [comment]
Enterprise-Deployment API was previously released to Maven:  https://mvnrepository.com/artifact/jakarta.enterprise.deploy/jakarta.enterprise.deploy-api/1.7.1
