### ISSUE TITLE
Prepare Enterprise Deployment project for Jakarta EE 8 Release

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/enterprise-deployment#30]
### Tasks

- [x] Update text files
- [x] Generate "boilerplate" specification project
- [x] Make a staging release
- [x] Generate Stand-alone TCK test results
- [x] Create a PR to jakartaee/specifications repository
- [x] Update the Jakarta EE API jar by submitting a PR to the [jakartaee-api](https://github.com/eclipse-ee4j/jakartaee-api) project

See [here](https://wiki.eclipse.org/How_to_Prepare_API_Projects_to_Jakarta_EE_8_Release) for detailed instructions.

**Comment by starksm64** [comment]
I'm working on updating the text files including javadoc

**Comment by m0mus** [comment]
PRs to jakartaee/specifications:
https://github.com/jakartaee/specifications/pull/65
https://github.com/jakartaee/specifications/pull/66

**Comment by kwsutter** [comment]
@m0mus What is the 1.7.3 release in staging?  Was that a mistake?  I just saw the jakartaee-api request for 1.7.2 as well.  Just verifying the correct version to be used for Jakarta EE 8.  Thanks.
