### ISSUE TITLE
Why still Java API? How is this Cloud related API?

### ISSUE THREAD

**Issue by Tibor17** [eclipse-ee4j/enterprise-deployment#4]
I remember Oracle promissed Java EE 8 would be Cloud related.
This did not happen and now I expect Java EE9 to be Cloud related.
Naturally this question has raised up.
Why `enterprise-deployment` is still Java based API and not the REST based API?
Different application servers have different mechanism to make the deployment.
I thought that Oracle will unify the deployment of WAR file to the Cloud environment.
I still thought that Oracle cooperating with Jelastic would just make this happen.
Me as a developer cannot imaging how I would call these interfaces so hardly, even if JBoss has more simplistic deployment via CLI. I am still missing OSGi deployment. But Language Architect in Oracle should create some simplistic way with limited features, best is the REST, where the deployment would be a standard and done from outside of Cloud to inside of application server, docker maybe and server-less system too.

**Comment by m0mus** [comment]
The whole Java EE is in transition to the Eclipse Foundation. This project is a part of Java EE and has been transferred already. There is no Java EE 9 anymore, there is Jakarta EE owned by the Eclipse Foundation (read more about it [here](https://jakarta.ee)). 
Oracle doesn't own Jakarta EE, Oracle is only but participating in its development on the same rights and conditions as other participants. 
I see that you have some suggestions and questions. The right place for discussions is EE4J community mailing list here: jakarta.ee-community@eclipse.org.

**Comment by jim-krueger** [comment]
Closing since this appears to have been answered.
